apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: logging
    app.kubernetes.io/version: v1.16
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentd
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/component: logging
    spec:
      # Use dedicated service account for Fluentd
      serviceAccount: fluentd
      
      # Allow scheduling on master nodes
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.16-1
        
        # Set resource limits and requests for stability
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 250m
            
        # Mount required volumes for log collection
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers 
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc
          
        # Configure Elasticsearch output
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: elasticsearch.monitoring.svc.cluster.local
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
          
      # Define volumes for log collection and configuration
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: fluentd-config