apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: ai-application-intake
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: application-processing
    app.kubernetes.io/component: api
    app.kubernetes.io/version: 1.0.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2 # Ensures high availability with minimum 2 replicas
  maxReplicas: 10 # Allows scaling up to 10 replicas to handle peak loads
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Scale up when CPU utilization exceeds 70%
    
    # Memory-based scaling  
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # Scale up when memory utilization exceeds 80%
  
  behavior:
    scaleUp:
      # Wait 60s before scaling up to avoid thrashing
      stabilizationWindowSeconds: 60
      policies:
        # Add up to 2 pods every 60 seconds
        - type: Pods
          value: 2
          periodSeconds: 60
    
    scaleDown:
      # Wait 5 minutes before scaling down to handle temporary load drops
      stabilizationWindowSeconds: 300
      policies:
        # Remove 1 pod every 2 minutes
        - type: Pods
          value: 1
          periodSeconds: 120