apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ai-application-intake
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: application-processing
    app.kubernetes.io/component: api
    app.kubernetes.io/version: 1.0.0
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api-gateway
  sessionAffinity: None