apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: api-gateway-secrets
    namespace: ai-application-intake
    labels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/part-of: application-processing
      security.kubernetes.io/auto-rotation: enabled
      security.kubernetes.io/rotation-interval: 90d
    annotations:
      kubernetes.io/last-rotated: ${LAST_ROTATED_TIMESTAMP}
      vault.hashicorp.com/agent-inject: "true"
  type: Opaque
  data:
    JWT_SECRET: ${JWT_SECRET}
    REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    AUTH0_API_KEY: ${AUTH0_API_KEY}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${AWS_REGION}
    API_ENCRYPTION_KEY: ${API_ENCRYPTION_KEY}
    MFA_SECRET_KEY: ${MFA_SECRET_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: document-processor-secrets
    namespace: ai-application-intake
    labels:
      app.kubernetes.io/name: document-processor
      app.kubernetes.io/part-of: application-processing
      security.kubernetes.io/auto-rotation: enabled
      security.kubernetes.io/rotation-interval: 90d
    annotations:
      kubernetes.io/last-rotated: ${LAST_ROTATED_TIMESTAMP}
      vault.hashicorp.com/agent-inject: "true"
  type: Opaque
  data:
    AWS_TEXTRACT_ACCESS_KEY: ${AWS_TEXTRACT_ACCESS_KEY}
    AWS_TEXTRACT_SECRET_KEY: ${AWS_TEXTRACT_SECRET_KEY}
    AWS_TEXTRACT_REGION: ${AWS_TEXTRACT_REGION}
    S3_ACCESS_KEY: ${S3_ACCESS_KEY}
    S3_SECRET_KEY: ${S3_SECRET_KEY}
    S3_REGION: ${S3_REGION}
    S3_BUCKET: ${S3_BUCKET}
    DOCUMENT_ENCRYPTION_KEY: ${DOCUMENT_ENCRYPTION_KEY}
    OCR_API_KEY: ${OCR_API_KEY}
    ML_MODEL_ACCESS_KEY: ${ML_MODEL_ACCESS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: email-service-secrets
    namespace: ai-application-intake
    labels:
      app.kubernetes.io/name: email-service
      app.kubernetes.io/part-of: application-processing
      security.kubernetes.io/auto-rotation: enabled
      security.kubernetes.io/rotation-interval: 90d
    annotations:
      kubernetes.io/last-rotated: ${LAST_ROTATED_TIMESTAMP}
      vault.hashicorp.com/agent-inject: "true"
  type: Opaque
  data:
    IMAP_USERNAME: ${IMAP_USERNAME}
    IMAP_PASSWORD: ${IMAP_PASSWORD}
    IMAP_HOST: ${IMAP_HOST}
    IMAP_PORT: ${IMAP_PORT}
    SMTP_USERNAME: ${SMTP_USERNAME}
    SMTP_PASSWORD: ${SMTP_PASSWORD}
    SMTP_HOST: ${SMTP_HOST}
    SMTP_PORT: ${SMTP_PORT}
    EMAIL_OAUTH_CLIENT_ID: ${EMAIL_OAUTH_CLIENT_ID}
    EMAIL_OAUTH_CLIENT_SECRET: ${EMAIL_OAUTH_CLIENT_SECRET}
    EMAIL_OAUTH_REFRESH_TOKEN: ${EMAIL_OAUTH_REFRESH_TOKEN}
    AWS_SES_ACCESS_KEY: ${AWS_SES_ACCESS_KEY}
    AWS_SES_SECRET_KEY: ${AWS_SES_SECRET_KEY}
    AWS_SES_REGION: ${AWS_SES_REGION}
    EMAIL_ENCRYPTION_KEY: ${EMAIL_ENCRYPTION_KEY}