apiVersion: v1
kind: List
items:
  # API Gateway Service Account
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: api-gateway-sa
      namespace: ai-application-intake
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: application-processing
        app.kubernetes.io/component: api
        security.ai-platform.io/audit-level: high
        security.ai-platform.io/rotation-policy: 24h
      annotations:
        description: Service account for API Gateway service with enhanced security controls
        security.ai-platform.io/token-expiry: 24h
        security.ai-platform.io/requires-mfa: "true"
        monitoring.ai-platform.io/alert-on-use: "true"

  # Document Processor Service Account
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: document-processor-sa
      namespace: ai-application-intake
      labels:
        app.kubernetes.io/name: document-processor
        app.kubernetes.io/part-of: application-processing
        app.kubernetes.io/component: processor
        security.ai-platform.io/audit-level: high
        security.ai-platform.io/rotation-policy: 24h
      annotations:
        description: Service account for Document Processor service with data processing permissions
        security.ai-platform.io/token-expiry: 24h
        security.ai-platform.io/data-access-level: sensitive
        monitoring.ai-platform.io/alert-on-use: "true"

  # Email Service Account
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: email-service-sa
      namespace: ai-application-intake
      labels:
        app.kubernetes.io/name: email-service
        app.kubernetes.io/part-of: application-processing
        app.kubernetes.io/component: email
        security.ai-platform.io/audit-level: high
        security.ai-platform.io/rotation-policy: 24h
      annotations:
        description: Service account for Email Service with email processing permissions
        security.ai-platform.io/token-expiry: 24h
        security.ai-platform.io/external-communication: "true"
        monitoring.ai-platform.io/alert-on-use: "true"