apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: monitoring
    part-of: observability
    tier: visualization
    managed-by: kubernetes
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    monitoring.dollarfunding.com/critical: "true"
    description: "Grafana dashboard service for system monitoring and metrics visualization"
    backup.dollarfunding.com/retention: "7d"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-grafana
  selector:
    app: grafana
    component: monitoring
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800