# Kubernetes API version v1.25+
apiVersion: v1
kind: Service

metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: metrics
  annotations:
    # Enable Prometheus scraping on this service
    prometheus.io/scrape: "true"
    # Define the port Prometheus is listening on
    prometheus.io/port: "9090"

spec:
  # Using ClusterIP as we want internal access only
  type: ClusterIP
  
  # Port configuration for Prometheus
  ports:
    - port: 9090          # Service port
      targetPort: 9090    # Container port
      protocol: TCP       # Using TCP protocol
      name: http         # Named port for easier reference
  
  # Selector to match Prometheus pods
  selector:
    app.kubernetes.io/name: prometheus